### ISSUE TITLE
Funktion mit deskriptiven Statistiken für metrische Variablen

### ISSUE THREAD

**Issue by Lukas107** [elstrippi/WissenschaftlichesArbeiten2023#1]
Aufgabe 3 a)

**Comment by elstrippi** [comment]
[Aufgabe 3a.txt](https://github.com/elstrippi/WissenschaftlichesArbeiten2023/files/10825803/Aufgabe.3a.txt)

Ich kann hier leider keine R-Datei hochladen, deshalb die Textdatei. Aber vielleicht könnt ihr trotzdem sagen, was ihr davon haltet. Ich hab noch die Möglichkeit für eine Ausgabe eingebaut. Haltet ihr das für übertrieben?

**Comment by Lukas107** [comment]
Ich glaube du solltest in deinem eigenen Branch den Code schreiben und dann eine Pull request schicken

**Comment by MaYEEET** [comment]
Ich finde auch die moments Library nicht

**Comment by elstrippi** [comment]
Das Paket musst du einmalig herunterladen. Mit install.packages("moments")
