### ISSUE TITLE
Fehler bei der Stichprobe 

### ISSUE THREAD

**Issue by MaYEEET** [elstrippi/WissenschaftlichesArbeiten2023#18]
Bei der Stichprobe sind die True nicht alle richtige Trues und werden deswegen im ersten moment nicht richtig eingelesen können wenn dsa nicht geht in den Funktionen nen workaround einbauen wäre aber besser das zu verbessern

**Comment by DialloKo** [comment]
Dann können wir einen Workaround einbauen

**Comment by DialloKo** [comment]
eigentlich es war nur ein TRUE als klein geschrieben, ich glaube das kann korrigieren
